version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: mtcg-postgres
    environment:
      - POSTGRES_DB=mtcg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mtcg"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
